service: dynamodb-streams
useDotenv: true

frameworkVersion: ">=1.21.0 <2.72.6"

provider:
  name: aws
  region: eu-central-1
  runtime: 'nodejs14.x'
  stage: ${sls:stage}
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "*"
  environment:
    ESHOST: ${ssm:/${env:AWS_ENV}/opensearch/ESHOST}
    ESPORT: ${ssm:/${env:AWS_ENV}/opensearch/ESPORT}
    ESUSER: ${ssm:/${env:AWS_ENV}/opensearch/ESUSER~true}
    ESPASS: ${ssm:/${env:AWS_ENV}/opensearch/ESPASS~true}

plugins:
  - serverless-esbuild
  - serverless-dynamo-stream-plugin

package:
  individually: true

functions:
  ${file(functions.yml)}
custom:
  accountID: ${ssm:/${env:AWS_ENV}/CURRENT_ACCOUNT_ID}
  esbuild:
    packagePath: ../../package.json
